### ISSUE TITLE
Missing default constructor in abstract class SCMDescriptorPW

### ISSUE THREAD

**Issue by kobotschick** [jenkinsci/jenkins.py#2]
The abstract class SCMDescriptorPW has no default constructor (without arguments).
That leads to a compile error when implementing inherited class.

[ERROR] C:\work\Jenkins\pytegrity-plugin \master\src\main\java\jenkins\plugins\pytegrity\PytegrityScm.java:[57,1] error: annotated classes mu
st have a public no-argument constructor

SourceCode:
   @Extension
    public static final class DescriptorImpl extends SCMDescriptorPW<PytegrityScm> {
        public descriptorimpl() {
                  execpython("descriptor_impl");
            }  
    }

**Comment by conyx** [comment]
Hi,

the class SCMDescriptor itself has no public contructor without argument...
so I suppose, you should write something like that:

public DescriptorImpl() {
    super(SomeYourRepositoryBrowserClass.class)
    execPython("descriptor_impl");
}

**Comment by kobotschick** [comment]
Hi,
adding the super function call into the default constructor works really fine.
You are right, there is no public constructor without argument in SCMDescriptor.

BTW: Thanks for your fast reply and really good job

**Comment by kobotschick** [comment]
The issue can be rejected/closed.
